### ISSUE TITLE
Gather Relevant Weather & Location Data

### ISSUE THREAD

**Issue by kramerc3** [brendanpayne/protifyapp#24]
### Story Description:
Create basic logic for compiling weather and location data from the device into a centrally accessible location to be used at the time of API calls.

#### Acceptance Criteria:
1. Relevant data for weather and location is gathered

2. Data is stored in a location accessible to other functions

#### Tasks:
- Locate the location data locally stored to the device
- Locate the weather data locally stored to the device
- Create variables for the data to be stored during runtime

**Comment by uc-mcreyntm** [comment]
Added very basic funtionality for getting user location information. Still need to add a lot of error checking and what not, but I was able to successfully store my logitude and lattitude into variables. I was not able to get it to work with the android emulator, maybe because the location feature was broken, but I was able to get it when using my physical phone

**Comment by uc-mcreyntm** [comment]
For weather data, it looks like we might need to get that from another source. I'm not sure if we can get weather data from android itself. Looking into this further.

**Comment by uc-mcreyntm** [comment]
Retrieve longitude and lattitude from device. Use that info to get weather data. Video linked below

https://github.com/brendanpayne/protifyapp/assets/89491042/d17f9671-2bb4-401d-a69e-c3c75d8ade7f

**Comment by uc-mcreyntm** [comment]
Rewrote API call to get all hourly weather forecast for the next 7 days. It compiles that list and outputs times when chances of rain are over 50%. This will help make more accurate determinations for suggesting new times for outdoor events

**Comment by uc-mcreyntm** [comment]
Created unit tests for weather data and confirmed they are passing
