### ISSUE TITLE
Day Breakdown

### ISSUE THREAD

**Issue by uc-mcreyntm** [brendanpayne/protifyapp#38]
### Story Description:
Create a new implementation of a "day breakdown" where it shows you the day in 30 minute or 1 hour increments, with the events diaplayed in "blocks" next to their corresponding times

#### Acceptance Criteria:

1. A function is created that will show the day breakdown in 30 or 60 minute increments

2.  Events can be added to the day breakdown

3.  Each event will have it's own block, where the size of the block represents the start and end time of the event

4. Live clock displays a horizontal red line across view showing the current time

#### Tasks:

- Create breakdown view
-  Add events to view
- Size event "block" correctly
-  Create live clock

#### Definition of Done:

- When a user clicks on a given day, the hourly breakdown will appear with all of their events

**Comment by uc-mcreyntm** [comment]
First implementation. Need to create parameters and, if time, add functionality for dealing with overlapping events and a live clock feature.



![Image](https://github.com/brendanpayne/protifyapp/assets/89491042/f666ef2b-2e01-4866-90f7-d35a952e8f3b)

**Comment by uc-mcreyntm** [comment]
I little insight to how I designed this class:

It's rendered in layered columns. On the left 10% is one column that displays the time in hours, with scaling to the events. On the right 90% is the bottom layer, which is a "divider" at each hour. On top of that is the events layers. The only way I was able to find to "stack" events like this was to stack transparent events before and after real events to set the height of the column. I found that if there were overlapping events, it would disrupt the height of the column and shift all of the events downward. To fix this, I made an algorithm that "layers" the events. Essentially, it calculate how many events are overlapping it and will assign it layer. The layers are then rendered indivdually on top of each other. In the picture, for example, "Standup" and "Study" are on layer 0, where Gym is on layer 1. To get Gym in the right spot, I make an invisible event that goes from 00:00 to 20:45, then Gym is placed below that. As you can see there are also modifiers to the layers so they are a bit smaller to avoid totally covering up other events, as well as different colors so they stand out.

Tweaked view to look a bit nicer. Added "layering" functionailty, so if there are overlapping events, the will partially cover each other. Added live clock. 

I added parameters to the class to make it a bit customizeable, but it's still a bit lacking. Let me know if you all want more customization on colors or what not.



![Image](https://github.com/brendanpayne/protifyapp/assets/89491042/fdfcc1a0-d78b-4052-9b5b-c81bc4049f13)

**Comment by uc-mcreyntm** [comment]
Since columns are rendered directly on top of each other, I'm running into the issue where you can't click on events under the most recently rendered column. This means that if there are any overlapping events, you can only click on the top layer. I've spent hours and hours trying to fix this issue, but I can't seem to work around it. If time contraints don't become a huge issue, this shuold be rewritten.

**Comment by brendanpayne** [comment]
Rewrote the Event Breakdown; got it down to ~325 lines of code. Currently only populates events on the screen. Clicking on events will navigate to details page (will be implemented with #21), and clicking on blank spaces will navigate to the add events page.

Currently displays on the homepage where the event card was.

Next step is to handle overlaying events. To avoid the issue Tom was having, I plan on cutting the width of cards in half to allow overlay in the event there is any (similar to how Teams does it). 

![Image](https://github.com/brendanpayne/protifyapp/assets/75294679/b0a35ed5-811f-4ca7-b480-d113d7c1f213)
